directories:
  output: dist
  buildResources: resources
appId: com.yourdomain.gta5tunercalculator
productName: MexicoCity-Tuner
files:
  - filter:
      - '**/*'
publish:
  - provider: github
    owner: Massimo1107
    repo: MexicoCity-Tuner
electronVersion: 22.3.27
